---
- hosts: loadbalancer_grp
  become: true
  tasks:
    - name: Check loadbalancer status
      command: service nginx status

    - name: Verify nginx is listening on port 80
      wait_for: port=80 timeout=1

- hosts: webserver_grp
  become: true
  tasks:
    - name: Check Apache 2 status
      command: service apache2 status

    - name: Verify apache is listening on port 80
      wait_for: port=80 timeout=1

- hosts: database_grp
  become: true
  tasks:
    - name: Check mysql status
      command: service mysql status

    - name: Verify mysql is listening on port 3306
      wait_for: host={{ ansible_default_ipv4.address }} port=3306 timeout=1

- hosts: control
  tasks:
    - name: verify end-to-end response
      uri: url=http://{{item}} return_content=yes
      with_items: "{{ groups.loadbalancer_grp }}"
      register: lb_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{ lb_index.results }}"

    - name: verify end-to-end database response
      uri: url=http://{{item}}/db return_content=yes
      with_items: "{{ groups.loadbalancer_grp }}"
      register: lbdb_index

    - fail: msg="index failed to return content"
      when: "'Database Connected' not in item.content"
      with_items: "{{ lbdb_index.results }}"

- hosts: loadbalancer
  tasks:
    - name: verify backend response
      uri: url=http://{{item}} return_content=yes
      with_items: "{{ groups.webserver_grp }}"
      register: app_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny {{item.item}}' not in item.content"
      with_items: "{{ app_index.results }}"
