---
# Bring stack down
- hosts: loadbalancer_grp
  become: true
  tasks:
    - service: name=nginx state=stopped

- hosts: webserver_grp
  become: true
  tasks:
    - service: name=apache2 state=stopped

# Restart database
- hosts: database_grp
  become: true
  tasks:
    - service: name=mysql state=restart

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=started

- hosts: loadbalancer_grp
  become: true
  tasks:
    - service: name=nginx state=stopped