---
# Bring stack down
- hosts: loadbalancer_grp
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webserver_grp
  become: true
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

# Restart database
- hosts: database_grp
  become: true
  tasks:
    - service: name=mysql state=restart
    - wait_for: port=3306 state=started

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80 #state defaults to started

- hosts: loadbalancer_grp
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80